updated to use cpath

diff --git a/bin/junc b/bin/junc
--- a/bin/junc
+++ b/bin/junc
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# usage: junc [-p] [-d] [-j junction-root] [-c name-length] [dir-path]
+# usage: junc [-d] [-j junction-root] [-c name-length] [-C clean] [dir-path]
 
 NC='\033[0m'
 RED='\033[0;31m'
@@ -10,21 +10,27 @@ BLUE='\033[0;34m'
 PURPLE='\033[0;35m'
 YELLOW='\033[1;33m'
 
+if ! hash cpath 2>/dev/null; then
+  >&2 printf "%b- cpath required, installing globally... -%b" "$CYAN" "$NC"
+  npm install -g cpath
+fi
+
 delete_junc=false
 junc_root="/c/junc"
 name_length=5
 dir_path="$PWD"
-
+clean_flag=false
 
 usage_short="${BLUE}usage: junc [-d] [-j junction-root] [-c name-length] [dir-path]"
 usage_long="$usage_short\n-d: delete junction at path (default: $delete_junc)"
 usage_long="$usage_long\n-j: path to junction root (default: $junc_root)"
 usage_long="$usage_long\n-c: length of randomly generated junction names (default: $name_length)"
+usage_long="$usage_long\n-C: cleanup junc directories (default: $clean_flag)"
 usage_long="$usage_long\ndir-path: path to directory getting junctioned (default: $dir_path)${NC}"
 
 usage_short="$usage_short\nuse -h to get supported command information.${NC}"
 
-options=":pdj:c:h"
+options=":pdj:c:Ch"
 shopt -u nocasematch
 OPTIND=1
 while getopts "$options" opt ; do
@@ -37,6 +43,9 @@ while getopts "$options" opt ; do
       ;;
     c )
       name_length="$OPTARG"
+      ;;
+    C )
+      clean_flag="$OPTARG"
       ;;
     h )
       >&2 printf "%b" "$usage_long" && exit 1
@@ -69,24 +78,7 @@ generate_name() {
   < /dev/urandom tr -dc a-z | head -c${1:-32};echo;
 }
 
-to_win_path() {
-  if [ "$1" ] ; then
-    # handle absolute
-    if [[ "$1" == /* ]] ; then
-      # strip leading slash and convert to backslash
-      win_path="$(printf "%s" "$1" | sed "s/^\///" | tr "/" "\\\\")"
-      # Add semicolon after drive
-      win_path="$(printf "%s:%s" "${win_path:0:1}" "${win_path:1}")"
-      printf "%s" "$win_path"
-    else
-      # convert to backslash
-      win_path="$(printf "%s" "$1" | tr "/" "\\\\")"
-      printf "%s" "$win_path"
-    fi
-  fi
-}
-
-win_dir_path="$(to_win_path "$dir_path")"
+win_dir_path="$(cpath -w "$dir_path")"
 
 if [ "$delete_junc" = true ] ; then
   cmd //c rmdir "$win_dir_path" &>/dev/null
@@ -101,7 +93,7 @@ while [ -e "$junc_path" ] ; do
   junc_path="$junc_root/$junc_name"
 done
 
-win_junc_path="$(to_win_path "$junc_path")"
+win_junc_path="$(cpath -w "$junc_path")"
 
 mkdir -p "$junc_root" &>/dev/null
 cmd //c mklink //J "$win_junc_path" "$win_dir_path" &>/dev/null
