updated to printf

diff --git a/bin/junc b/bin/junc
--- a/bin/junc
+++ b/bin/junc
@@ -17,7 +17,7 @@ dir_path="$PWD"
 
 
 usage_short="${BLUE}usage: junc [-d] [-j junction-root] [-c name-length] [dir-path]"
-usage_long="$usage_long\n-d: delete junction at path (default: $delete_junc)"
+usage_long="$usage_short\n-d: delete junction at path (default: $delete_junc)"
 usage_long="$usage_long\n-j: path to junction root (default: $junc_root)"
 usage_long="$usage_long\n-c: length of randomly generated junction names (default: $name_length)"
 usage_long="$usage_long\ndir-path: path to directory getting junctioned (default: $dir_path)${NC}"
@@ -39,22 +39,22 @@ while getopts "$options" opt ; do
       name_length="$OPTARG"
       ;;
     h )
-      >&2 printf "%s" "$usage_long" && exit 1
+      >&2 printf "%b" "$usage_long" && exit 1
       exit 0
       ;;
     \?)
-      >&2 printf "%s" "unknown option: -$OPTARG"
-      >&2 printf "%s" "$usage_short"
+      >&2 printf "%b" "unknown option: -$OPTARG"
+      >&2 printf "%b" "$usage_short"
       exit 1
       ;;
     : )
-      >&2 printf "%s" "missing option argument for -$OPTARG"
-      >&2 printf "%s" "$usage_short"
+      >&2 printf "%b" "missing option argument for -$OPTARG"
+      >&2 printf "%b" "$usage_short"
       exit 1
       ;;
     * )
-      >&2 printf "%s" "unimplemented option: -$OPTARG"
-      >&2 printf "%s" "$usage_short"
+      >&2 printf "%b" "unimplemented option: -$OPTARG"
+      >&2 printf "%b" "$usage_short"
       exit 1
     esac
 done
